openapi: 3.0.0
info:
  title: Follow Management
  description: |
    VAPI for managing a user's followers. 
    Users can follow other users to view each other's feeds.
  version: "1.0.0"

paths:
  /get-followers:
    get:
      summary: Retrieve followers of a user
      parameters:
        - in: query
          name: user_id
          required: true
          schema:
            type: string
          description: The ID of the user to retrieve followers for
      responses:
        '200':
          description: Successfully retrieved followers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FollowInfo'
        '400':
          description: Missing user-id
        '405':
          description: Method not allowed

  /user-follow:
    post:
      summary: Follow a user
      parameters:
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
          description: Bearer token required to authorize the request
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FollowRequest'
      responses:
        '200':
          description: Successfully followed user
        '400':
          description: Missing user-id or target-user or already following
        '401':
          description: Unauthorized
        '405':
          description: Method not allowed

  /user-unfollow:
    delete:
      summary: Unfollow a user
      parameters:
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
          description: Bearer token required to authorize the request
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              user_id:
                type: string
                description: ID of the user trying to follow another user
              target_user_id:
                type: string
                description: ID of the target user to be followed
      responses:
        '200':
          description: Successfully unfollowed user
        '400':
          description: Missing user-id or target-user or not following
        '401':
          description: Unauthorized
        '405':
          description: Method not alone

components:
  schemas:
    Follower:
      type: object
      properties:
        id:
          type: string
        user_id:
          type: string
        target_user_id:
          type: string
        created_at:
          type: string
          format: date-time

    FollowInfo:
      type: object
      properties:
        user_id:
          type: string
          description: ID of the user
        target_user_id:
          type: string
          description: ID of the user being followed

    FollowRequest:
      type: object
      required:
        - user_id
        - target_user_id
      properties:
        user_id:
          type: string
          description: ID of the user who is initiating the follow
        target_user_id:
          type: string
          description: ID of the user to be followed or unfollowed
