openapi: 3.0.0
info:
  title: Task Management API
  description: This is an API for a task management system, which allows clients to manage their todo tasks efficiently.
  version: 1.0.0
servers:
  - url: '{API Reference home page URL}'
    description: Production server

paths:
  /tasks:
    get:
      summary: Retrieve all tasks
      description: Returns a list of all tasks.
      responses:
        '200':
          description: A list of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      summary: Create a new task
      description: Creates a new task with the provided details.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '200':
          description: Task created

  /tasks/{taskId}:
    parameters:
      - name: taskId
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Retrieve a task by ID
      description: Returns a single task based on the ID provided.
      responses:
        '200':
          description: Detailed task information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
    put:
      summary: Update an existing task
      description: Updates the details of an existing task.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '200':
          description: Task updated
    delete:
      summary: Delete a task
      description: Deletes a task based on the ID provided.
      responses:
        '200':
          description: Task deleted

  /tasks/deadline:
    get:
      summary: Retrieve tasks by deadline
      description: Returns tasks sorted by their deadlines.
      parameters:
        - name: deadline
          in: query
          required: true
          schema:
            type: string
            format: date
      responses:
        '200':
          description: List of tasks by deadline

  /tasks/weekly:
    get:
      summary: Retrieve weekly tasks
      description: Returns tasks that are set for the current week.
      responses:
        '200':
          description: List of weekly tasks

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        deadline:
          type: string
          format: date
        completed:
          type: boolean
